
import type { Astrologer, Transaction, ChatMessage, Product, KarmaTransaction, LiveSession } from './types';

export const astrologers: Astrologer[] = [
  {
    id: '1',
    name: 'Astro Neha',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=1888&auto=format&fit=crop',
    skills: ['Vedic', 'Tarot', 'Numerology'],
    experience: 10,
    rating: 4.9,
    reviews: 1204,
    price: 25,
    language: 'Hindi',
    status: 'online',
    bio: 'Expert in Vedic astrology with a decade of experience in solving life problems.',
  },
  {
    id: '2',
    name: 'Guru Ramesh',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=1887&auto=format&fit=crop',
    skills: ['Vastu', 'Palmistry'],
    experience: 15,
    rating: 4.8,
    reviews: 987,
    price: 30,
    language: 'English',
    status: 'busy',
    bio: 'Vastu and Palmistry specialist helping clients achieve harmony and success.',
  },
  {
    id: '3',
    name: 'Priya Sharma',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=1961&auto=format&fit=crop',
    skills: ['Tarot Reader', 'Psychic'],
    experience: 8,
    rating: 4.9,
    reviews: 2341,
    price: 20,
    language: 'English',
    status: 'online',
    bio: 'Intuitive Tarot reader and psychic providing clarity and guidance for your journey.',
  },
  {
    id: '4',
    name: 'Ankit Patel',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1887&auto=format&fit=crop',
    skills: ['KP System', 'Numerology'],
    experience: 5,
    rating: 4.7,
    reviews: 754,
    price: 15,
    language: 'Hindi',
    status: 'away',
    bio: 'Specializing in KP astrology and numerology to provide accurate predictions.',
  },
  {
    id: '5',
    name: 'Divya Singh',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=1887&auto=format&fit=crop',
    skills: ['Vedic', 'Face Reading'],
    experience: 12,
    rating: 4.8,
    reviews: 1500,
    price: 28,
    language: 'English',
    status: 'online',
    bio: 'Combining ancient Vedic wisdom with the art of face reading to reveal your destiny.',
  },
  {
    id: '6',
    name: 'Rajesh Kumar',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=1887&auto=format&fit=crop',
    skills: ['Nadi Astrology', 'Prashna'],
    experience: 20,
    rating: 4.9,
    reviews: 3200,
    price: 40,
    language: 'Tamil',
    status: 'busy',
    bio: 'Master of Nadi Astrology, uncovering past, present, and future from ancient palm leaves.',
  },
  {
    id: '7',
    name: 'Astro Kavya',
    avatar: 'https://images.unsplash.com/photo-1557053910-d9eadeed1c58?q=80&w=1887&auto=format&fit=crop',
    skills: ['Vedic', 'Prashna'],
    experience: 9,
    rating: 4.8,
    reviews: 850,
    price: 22,
    language: 'Kannada',
    status: 'online',
    bio: 'Expert in Vedic astrology with deep knowledge of Prashna kundali.',
  },
  {
    id: '8',
    name: 'Pandit Sriram',
    avatar: 'https://images.unsplash.com/photo-1566753323558-f4e0952af115?q=80&w=1921&auto=format&fit=crop',
    skills: ['Numerology', 'Palmistry'],
    experience: 12,
    rating: 4.7,
    reviews: 1100,
    price: 27,
    language: 'Telugu',
    status: 'online',
    bio: 'Providing guidance through the science of numbers and the art of palmistry.',
  },
];

export const transactions: Transaction[] = [
  { id: 'txn1', date: '2023-10-26', description: 'Wallet Recharge', amount: 500, type: 'credit', status: 'success' },
  { id: 'txn2', date: '2023-10-25', description: 'Chat with Astro Neha', amount: 150, type: 'debit', status: 'success' },
  { id: 'txn3', date: '2023-10-24', description: 'Wallet Recharge', amount: 200, type: 'credit', status: 'success' },
  { id: 'txn4', date: '2023-10-22', description: 'Call with Guru Ramesh', amount: 300, type: 'debit', status: 'success' },
  { id: 'txn5', date: '2023-10-20', description: 'Failed Recharge', amount: 100, type: 'credit', status: 'failed' },
];

export const chatMessages: ChatMessage[] = [];

export const products: Product[] = [
  {
    id: 'prod-001',
    name: '7 Chakra Healing Bracelet',
    category: 'Bracelets',
    purpose: ['Healing', 'Protection'],
    price: 899,
    originalPrice: 1299,
    images: ['/c1.webp', '/c2.webp', '/c3.webp'],
    description: 'A beautiful bracelet made with 7 different healing crystals, designed to balance your chakras and promote well-being. Each stone corresponds to a specific chakra.',
    benefits: ['Balances all seven chakras', 'Promotes emotional stability', 'Enhances mental clarity and focus', 'Brings a sense of peace and harmony'],
    howToWear: 'Wear on your left wrist to receive its healing energy. Cleanse once a week by placing it under moonlight or with sage smoke.',
    rating: 4.8,
    reviews: 256,
  },
  {
    id: 'prod-002',
    name: 'Shree Yantra',
    category: 'Yantras',
    purpose: ['Money Magnet'],
    price: 1499,
    originalPrice: 1999,
    images: ['/c2.webp'],
    description: 'The Shree Yantra is one of the most powerful and auspicious yantras. It is a source of attaining all worldly desires & fulfilling all wishes through cosmic power.',
    benefits: ['Attracts wealth and prosperity', 'Helps in clearing financial blockages', 'Brings success in business and career', 'Promotes a positive flow of energy'],
    howToWear: 'Place in your home or office in the North-East direction. Worship it daily for best results.',
    rating: 4.9,
    reviews: 412,
  },
  {
    id: 'prod-003',
    name: 'Rose Quartz Love Pendant',
    category: 'Pendants',
    purpose: ['Love'],
    price: 799,
    images: ['/c5.webp'],
    description: 'A stunning pendant made from genuine Rose Quartz, the stone of unconditional love. It helps open the heart to give and receive love.',
    benefits: ['Attracts romantic love', 'Strengthens existing relationships', 'Promotes self-love and acceptance', 'Heals emotional wounds'],
    howToWear: 'Wear it close to your heart. Best worn on a Friday. Cleanse regularly with water.',
    rating: 4.7,
    reviews: 189,
  },
  {
    id: 'prod-004',
    name: 'Panchmukhi Rudraksha',
    category: 'Rudraksha',
    purpose: ['Protection', 'Healing'],
    price: 599,
    originalPrice: 899,
    images: ['/c6.webp'],
    description: 'An authentic 5-faced (Panchmukhi) Rudraksha bead. It represents Lord Shiva and is known for its powerful protective and healing energies.',
    benefits: ['Provides protection from negative energies', 'Calms the mind and reduces stress', 'Improves health and well-being', 'Enhances spiritual growth'],
    howToWear: 'Can be worn as a pendant or bracelet. It is best to wear it after getting it blessed. Avoid wearing it during sleep.',
    rating: 4.9,
    reviews: 512,
  },
    {
    id: 'prod-005',
    name: 'Money Magnet Pyrite Bracelet',
    category: 'Bracelets',
    purpose: ['Money Magnet'],
    price: 999,
    originalPrice: 1499,
    images: ['/c7.webp'],
    description: 'Attract wealth and abundance with this powerful Pyrite bracelet. Known as "Fool\'s Gold," Pyrite is a potent stone for manifestation and financial success.',
    benefits: ['Attracts wealth and opportunities', 'Boosts confidence and willpower', 'Blocks negative energy', 'Enhances creativity and ambition'],
    howToWear: 'Wear on your non-dominant hand to attract opportunities. Cleanse with sound or smoke, avoid water.',
    rating: 4.8,
    reviews: 320,
  },
  {
    id: 'prod-006',
    name: 'Amethyst Healing Gemstone',
    category: 'Gemstones',
    purpose: ['Healing'],
    price: 699,
images: ['/c3.webp'],
    description: 'A high-quality tumbled Amethyst gemstone. Amethyst is a powerful and protective stone with a high spiritual vibration.',
    benefits: ['Calms the mind and relieves stress', 'Enhances intuition and psychic abilities', 'Helps in overcoming addictions', 'Promotes restful sleep'],
    howToWear: 'Keep it in your pocket, place it on your desk, or meditate with it. Can also be placed under your pillow.',
    rating: 4.7,
    reviews: 154,
  },
];

export const karmaTransactions: KarmaTransaction[] = [
    { id: 'kp1', date: '2023-11-05', description: 'Daily Login Bonus', points: 5, type: 'earned' },
    { id: 'kp2', date: '2023-11-04', description: 'Referred a friend: friend@example.com', points: 50, type: 'earned' },
    { id: 'kp3', date: '2023-11-04', description: 'Redeemed: ₹100 off on consultation', points: 500, type: 'spent' },
    { id: 'kp4', date: '2023-11-03', description: 'First chat with Astro Priya', points: 20, type: 'earned' },
    { id: 'kp5', date: '2023-11-02', description: 'Daily Login Bonus', points: 5, type: 'earned' },
];



export const liveSessions: LiveSession[] = [
  {
    id: 'live-1',
    title: 'Planetary Transits & Your Career',
    description: 'Join Astro Neha as she discusses how the current planetary movements can impact your professional life.',
    astrologer: astrologers[0], // Astro Neha
    status: 'live',
    startTime: new Date().toISOString(),
    image: '/mc2.webp'
  },
  {
    id: 'live-2',
    title: 'Understanding Vastu for Home Harmony',
    description: 'Guru Ramesh will share tips on how to improve the energy in your home for peace and prosperity.',
    astrologer: astrologers[1], // Guru Ramesh
    status: 'upcoming',
    startTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(), // 2 hours from now
    image: '/mc3.jfif'
  },
  {
    id: 'live-3',
    title: 'Tarot Tuesday: Weekly Reading',
    description: 'Get your weekly tarot guidance with Priya Sharma. We will explore the cards for the week ahead.',
    astrologer: astrologers[2], // Priya Sharma
    status: 'upcoming',
    startTime: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(), // 1 day from now
    image: '/mc4.jfif'
  },
];
